List<Map<String, String>> carModelDescriptions = [
  {
    "model": "2020",
    "make": "Toyota",
    "mileage": "25,000 km",
    "price": "\$28,500",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar1.jpg",
  },
  {
    "model": "2022",
    "make": "Honda",
    "mileage": "15,200 km",
    "price": "\$32,000",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar1.jpg",
  },
  {
    "model": "2021",
    "make": "Ford",
    "mileage": "20,500 km",
    "price": "\$30,700",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar2.png",
  },
  {
    "model": "2023",
    "make": "Chevrolet",
    "mileage": "12,800 km",
    "price": "\$35,900",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar3.png",
  },
  {
    "model": "2020",
    "make": "Mercedes-Benz",
    "mileage": "30,000 km",
    "price": "\$45,200",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar4.png",
  },
  {
    "model": "2022",
    "make": "Audi",
    "mileage": "18,700 km",
    "price": "\$42,500",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar1.jpg",
  },
  {
    "model": "2021",
    "make": "BMW",
    "mileage": "22,300 km",
    "price": "\$48,600",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar6.png",
  },
  {
    "model": "2020",
    "make": "Lexus",
    "mileage": "27,500 km",
    "price": "\$38,900",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar7.png",
  },
  {
    "model": "2023",
    "make": "Tesla",
    "mileage": "10,000 km",
    "price": "\$55,000",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar2.jpg",
  },
  {
    "model": "2022",
    "make": "Hyundai",
    "mileage": "16,500 km",
    "price": "\$27,800",
    "des": "ssssssssssssssssssssssss",
    "image": "assets/images/whitecar3.png",
  },
  // Add more examples as needed
];
// -------------------------------

List<Map<String, String>> suvCarModelDescriptions = [
  {
    "model": "2020",
    "make": "Chevrolet",
    "mileage": "22,800 km",
    "price": "\$27,600",
    "des": "Pellentesque ac mi tincidunt, fermentum elit in, vehicula ex.",
    "image": "assets/images/suv4.png",
  },
  {
    "model": "2022",
    "make": "Jeep",
    "mileage": "14,500 km",
    "price": "\$38,000",
    "des":
        "Vivamus aliquam leo ut felis pharetra, id bibendum felis facilisis.",
    "image": "assets/images/suv5.png",
  },
  {
    "model": "2022",
    "make": "Toyota",
    "mileage": "18,200 km",
    "price": "\$32,500",
    "des": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "image": "assets/images/suv1.png",
  },
  {
    "model": "2021",
    "make": "Honda",
    "mileage": "15,700 km",
    "price": "\$29,900",
    "des": "Nulla facilisi. Sed vel eleifend mauris, nec commodo velit.",
    "image": "assets/images/suv2.png",
  },
  {
    "model": "2023",
    "make": "Ford",
    "mileage": "12,300 km",
    "price": "\$35,200",
    "des": "Duis at justo consequat, sodales mi at, convallis ipsum.",
    "image": "assets/images/suv3.png",
  },
  {
    "model": "2021",
    "make": "Subaru",
    "mileage": "17,600 km",
    "price": "\$33,700",
    "des": "Fusce volutpat tellus in pretium volutpat.",
    "image": "assets/images/suv6.png",
  },
  {
    "model": "2023",
    "make": "Nissan",
    "mileage": "11,900 km",
    "price": "\$36,900",
    "des": "In lacinia augue at magna vulputate, et rutrum nunc tristique.",
    "image": "assets/images/suv7.png",
  },
  {
    "model": "2020",
    "make": "Kia",
    "mileage": "21,400 km",
    "price": "\$31,800",
    "des":
        "Phasellus posuere ligula nec lorem rhoncus, at posuere lectus condimentum.",
    "image": "assets/images/suv8.png",
  },
  {
    "model": "2022",
    "make": "Mazda",
    "mileage": "16,200 km",
    "price": "\$30,400",
    "des": "Curabitur sit amet velit non libero luctus posuere.",
    "image": "assets/images/suv9.png",
  },
  {
    "model": "2021",
    "make": "GMC",
    "mileage": "19,300 km",
    "price": "\$34,500",
    "des": "Integer congue est in ligula commodo, nec volutpat nisl fermentum.",
    "image": "assets/images/suv10.png",
  },
];

// =======================================================
List<Map<String, String>> SedanCarModelDescriptions = [
  {
    "model": "2020",
    "make": "Chevrolet",
    "mileage": "22,800 km",
    "price": "\$27,600",
    "des": "Pellentesque ac mi tincidunt, fermentum elit in, vehicula ex.",
    "image": "assets/images/suv4.png",
  },
  {
    "model": "2022",
    "make": "Jeep",
    "mileage": "14,500 km",
    "price": "\$38,000",
    "des":
        "Vivamus aliquam leo ut felis pharetra, id bibendum felis facilisis.",
    "image": "assets/images/suv5.png",
  },
  {
    "model": "2022",
    "make": "Toyota",
    "mileage": "18,200 km",
    "price": "\$32,500",
    "des": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "image": "assets/images/suv1.png",
  },
  {
    "model": "2021",
    "make": "Honda",
    "mileage": "15,700 km",
    "price": "\$29,900",
    "des": "Nulla facilisi. Sed vel eleifend mauris, nec commodo velit.",
    "image": "assets/images/suv2.png",
  },
  {
    "model": "2023",
    "make": "Ford",
    "mileage": "12,300 km",
    "price": "\$35,200",
    "des": "Duis at justo consequat, sodales mi at, convallis ipsum.",
    "image": "assets/images/suv3.png",
  },
  {
    "model": "2021",
    "make": "Subaru",
    "mileage": "17,600 km",
    "price": "\$33,700",
    "des": "Fusce volutpat tellus in pretium volutpat.",
    "image": "assets/images/suv6.png",
  },
  {
    "model": "2023",
    "make": "Nissan",
    "mileage": "11,900 km",
    "price": "\$36,900",
    "des": "In lacinia augue at magna vulputate, et rutrum nunc tristique.",
    "image": "assets/images/suv7.png",
  },
  {
    "model": "2020",
    "make": "Kia",
    "mileage": "21,400 km",
    "price": "\$31,800",
    "des":
        "Phasellus posuere ligula nec lorem rhoncus, at posuere lectus condimentum.",
    "image": "assets/images/suv8.png",
  },
  {
    "model": "2022",
    "make": "Mazda",
    "mileage": "16,200 km",
    "price": "\$30,400",
    "des": "Curabitur sit amet velit non libero luctus posuere.",
    "image": "assets/images/suv9.png",
  },
  {
    "model": "2021",
    "make": "GMC",
    "mileage": "19,300 km",
    "price": "\$34,500",
    "des": "Integer congue est in ligula commodo, nec volutpat nisl fermentum.",
    "image": "assets/images/suv10.png",
  },
];
// ----------------------------------------------------

List<Map<String, String>> HatchCarModelDescriptions = [
  {
    "model": "2020",
    "make": "Chevrolet",
    "mileage": "22,800 km",
    "price": "\$27,600",
    "des": "Pellentesque ac mi tincidunt, fermentum elit in, vehicula ex.",
    "image": "assets/images/suv4.png",
  },
  {
    "model": "2022",
    "make": "Jeep",
    "mileage": "14,500 km",
    "price": "\$38,000",
    "des":
        "Vivamus aliquam leo ut felis pharetra, id bibendum felis facilisis.",
    "image": "assets/images/suv5.png",
  },
  {
    "model": "2022",
    "make": "Toyota",
    "mileage": "18,200 km",
    "price": "\$32,500",
    "des": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "image": "assets/images/suv1.png",
  },
  {
    "model": "2021",
    "make": "Honda",
    "mileage": "15,700 km",
    "price": "\$29,900",
    "des": "Nulla facilisi. Sed vel eleifend mauris, nec commodo velit.",
    "image": "assets/images/suv2.png",
  },
  {
    "model": "2023",
    "make": "Ford",
    "mileage": "12,300 km",
    "price": "\$35,200",
    "des": "Duis at justo consequat, sodales mi at, convallis ipsum.",
    "image": "assets/images/suv3.png",
  },
  {
    "model": "2021",
    "make": "Subaru",
    "mileage": "17,600 km",
    "price": "\$33,700",
    "des": "Fusce volutpat tellus in pretium volutpat.",
    "image": "assets/images/suv6.png",
  },
  {
    "model": "2023",
    "make": "Nissan",
    "mileage": "11,900 km",
    "price": "\$36,900",
    "des": "In lacinia augue at magna vulputate, et rutrum nunc tristique.",
    "image": "assets/images/suv7.png",
  },
  {
    "model": "2020",
    "make": "Kia",
    "mileage": "21,400 km",
    "price": "\$31,800",
    "des":
        "Phasellus posuere ligula nec lorem rhoncus, at posuere lectus condimentum.",
    "image": "assets/images/suv8.png",
  },
  {
    "model": "2022",
    "make": "Mazda",
    "mileage": "16,200 km",
    "price": "\$30,400",
    "des": "Curabitur sit amet velit non libero luctus posuere.",
    "image": "assets/images/suv9.png",
  },
  {
    "model": "2021",
    "make": "GMC",
    "mileage": "19,300 km",
    "price": "\$34,500",
    "des": "Integer congue est in ligula commodo, nec volutpat nisl fermentum.",
    "image": "assets/images/suv10.png",
  },
];
